// lib/theme/app_colors.dart
import 'package:flutter/cupertino.dart';

class AppColors {
  // Background colors
  final Color primary;
  final Color secondary;
  final Color background;
  final Color surface;
  final Color surfaceSecondary;

  // Text colors
  final Color textPrimary;
  final Color textSecondary;
  final Color textTertiary;

  // Terminal colors
  final Color terminalBackground;
  final Color terminalForeground;
  final Color terminalCursor;
  final Color terminalSelection;
  final Color terminalPrompt;

  // ANSI colors
  final Color terminalBlack;
  final Color terminalRed;
  final Color terminalGreen;
  final Color terminalYellow;
  final Color terminalBlue;
  final Color terminalMagenta;
  final Color terminalCyan;
  final Color terminalWhite;
  final Color terminalBrightBlack;
  final Color terminalBrightRed;
  final Color terminalBrightGreen;
  final Color terminalBrightYellow;
  final Color terminalBrightBlue;
  final Color terminalBrightMagenta;
  final Color terminalBrightCyan;
  final Color terminalBrightWhite;

  // Accent colors
  final Color accent;
  final Color success;
  final Color error;
  final Color warning;

  // UI elements
  final Color border;
  final Color divider;
  final Color hover;
  final Color cardBackground;
  final Color inputBackground;

  const AppColors({
    required this.primary,
    required this.secondary,
    required this.background,
    required this.surface,
    required this.surfaceSecondary,
    required this.textPrimary,
    required this.textSecondary,
    required this.textTertiary,
    required this.terminalBackground,
    required this.terminalForeground,
    required this.terminalCursor,
    required this.terminalSelection,
    required this.terminalPrompt,
    required this.terminalBlack,
    required this.terminalRed,
    required this.terminalGreen,
    required this.terminalYellow,
    required this.terminalBlue,
    required this.terminalMagenta,
    required this.terminalCyan,
    required this.terminalWhite,
    required this.terminalBrightBlack,
    required this.terminalBrightRed,
    required this.terminalBrightGreen,
    required this.terminalBrightYellow,
    required this.terminalBrightBlue,
    required this.terminalBrightMagenta,
    required this.terminalBrightCyan,
    required this.terminalBrightWhite,
    required this.accent,
    required this.success,
    required this.error,
    required this.warning,
    required this.border,
    required this.divider,
    required this.hover,
    required this.cardBackground,
    required this.inputBackground,
  });

  // Dark theme (default)
  static const dark = AppColors(
    primary: Color(0xFF00D9FF),
    secondary: Color(0xFF00B8D4),
    background: Color(0xFF121212),
    surface: Color(0xFF1E1E1E),
    surfaceSecondary: Color(0xFF252525),
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xFFB0B0B0),
    textTertiary: Color(0xFF666666),
    terminalBackground: Color(0xFF1E1E1E),
    terminalForeground: Color(0xFFFFFFFF),
    terminalCursor: Color(0xFF00FF00),
    terminalSelection: Color(0xFF444444),
    terminalPrompt: Color(0xFF00FF00),
    terminalBlack: Color(0xFF000000),
    terminalRed: Color(0xFFCD3131),
    terminalGreen: Color(0xFF0DBC79),
    terminalYellow: Color(0xFFE5E510),
    terminalBlue: Color(0xFF2472C8),
    terminalMagenta: Color(0xFFBC3FBC),
    terminalCyan: Color(0xFF11A8CD),
    terminalWhite: Color(0xFFE5E5E5),
    terminalBrightBlack: Color(0xFF666666),
    terminalBrightRed: Color(0xFFF14C4C),
    terminalBrightGreen: Color(0xFF23D18B),
    terminalBrightYellow: Color(0xFFF5F543),
    terminalBrightBlue: Color(0xFF3B8EEA),
    terminalBrightMagenta: Color(0xFFD670D6),
    terminalBrightCyan: Color(0xFF29B8DB),
    terminalBrightWhite: Color(0xFFFFFFFF),
    accent: Color(0xFF00D9FF),
    success: Color(0xFF0DBC79),
    error: Color(0xFFCD3131),
    warning: Color(0xFFE5E510),
    border: Color(0xFF2C2C2C),
    divider: Color(0xFF2C2C2C),
    hover: Color(0xFF2C2C2C),
    cardBackground: Color(0xFF252525),
    inputBackground: Color(0xFF2C2C2C),
  );

  // Light theme
  static const light = AppColors(
    primary: Color(0xFF007AFF),
    secondary: Color(0xFF5AC8FA),
    background: Color(0xFFF2F2F7),
    surface: Color(0xFFFFFFFF),
    surfaceSecondary: Color(0xFFF9F9F9),
    textPrimary: Color(0xFF000000),
    textSecondary: Color(0xFF666666),
    textTertiary: Color(0xFF999999),
    terminalBackground: Color(0xFFEDEDED),
    terminalForeground: Color(0xFF000000),
    terminalCursor: Color(0xFF007AFF),
    terminalSelection: Color(0xFFD3D3D3),
    terminalPrompt: Color(0xFF00AA00),
    terminalBlack: Color(0xFF000000),
    terminalRed: Color(0xFFCD3131),
    terminalGreen: Color(0xFF00AA00),
    terminalYellow: Color(0xFFCCCC00),
    terminalBlue: Color(0xFF0066CC),
    terminalMagenta: Color(0xFFCC00CC),
    terminalCyan: Color(0xFF00CCCC),
    terminalWhite: Color(0xFFCCCCCC),
    terminalBrightBlack: Color(0xFF666666),
    terminalBrightRed: Color(0xFFFF6B6B),
    terminalBrightGreen: Color(0xFF00DD00),
    terminalBrightYellow: Color(0xFFFFFF00),
    terminalBrightBlue: Color(0xFF3399FF),
    terminalBrightMagenta: Color(0xFFFF00FF),
    terminalBrightCyan: Color(0xFF00FFFF),
    terminalBrightWhite: Color(0xFFFFFFFF),
    accent: Color(0xFF007AFF),
    success: Color(0xFF34C759),
    error: Color(0xFFFF3B30),
    warning: Color(0xFFFF9500),
    border: Color(0xFFE5E5EA),
    divider: Color(0xFFE5E5EA),
    hover: Color(0xFFF2F2F7),
    cardBackground: Color(0xFFFFFFFF),
    inputBackground: Color(0xFFF2F2F7),
  );

  // Nord theme
  static const nord = AppColors(
    primary: Color(0xFF88C0D0),
    secondary: Color(0xFF81A1C1),
    background: Color(0xFF2E3440),
    surface: Color(0xFF3B4252),
    surfaceSecondary: Color(0xFF434C5E),
    textPrimary: Color(0xFFECEFF4),
    textSecondary: Color(0xFFD8DEE9),
    textTertiary: Color(0xFF4C566A),
    terminalBackground: Color(0xFF2E3440),
    terminalForeground: Color(0xFFD8DEE9),
    terminalCursor: Color(0xFF88C0D0),
    terminalSelection: Color(0xFF4C566A),
    terminalPrompt: Color(0xFFA3BE8C),
    terminalBlack: Color(0xFF3B4252),
    terminalRed: Color(0xFFBF616A),
    terminalGreen: Color(0xFFA3BE8C),
    terminalYellow: Color(0xFFEBCB8B),
    terminalBlue: Color(0xFF81A1C1),
    terminalMagenta: Color(0xFFB48EAD),
    terminalCyan: Color(0xFF88C0D0),
    terminalWhite: Color(0xFFE5E9F0),
    terminalBrightBlack: Color(0xFF4C566A),
    terminalBrightRed: Color(0xFFBF616A),
    terminalBrightGreen: Color(0xFFA3BE8C),
    terminalBrightYellow: Color(0xFFEBCB8B),
    terminalBrightBlue: Color(0xFF81A1C1),
    terminalBrightMagenta: Color(0xFFB48EAD),
    terminalBrightCyan: Color(0xFF8FBCBB),
    terminalBrightWhite: Color(0xFFECEFF4),
    accent: Color(0xFF88C0D0),
    success: Color(0xFFA3BE8C),
    error: Color(0xFFBF616A),
    warning: Color(0xFFEBCB8B),
    border: Color(0xFF4C566A),
    divider: Color(0xFF4C566A),
    hover: Color(0xFF434C5E),
    cardBackground: Color(0xFF3B4252),
    inputBackground: Color(0xFF434C5E),
  );

  // Monokai theme
  static const monokai = AppColors(
    primary: Color(0xFFF92672),
    secondary: Color(0xFFAE81FF),
    background: Color(0xFF272822),
    surface: Color(0xFF3E3D32),
    surfaceSecondary: Color(0xFF49483E),
    textPrimary: Color(0xFFF8F8F2),
    textSecondary: Color(0xFF75715E),
    textTertiary: Color(0xFF5E5D51),
    terminalBackground: Color(0xFF272822),
    terminalForeground: Color(0xFFF8F8F2),
    terminalCursor: Color(0xFFF8F8F0),
    terminalSelection: Color(0xFF49483E),
    terminalPrompt: Color(0xFFA6E22E),
    terminalBlack: Color(0xFF272822),
    terminalRed: Color(0xFFF92672),
    terminalGreen: Color(0xFFA6E22E),
    terminalYellow: Color(0xFFF4BF75),
    terminalBlue: Color(0xFF66D9EF),
    terminalMagenta: Color(0xFFAE81FF),
    terminalCyan: Color(0xFFA1EFE4),
    terminalWhite: Color(0xFFF8F8F2),
    terminalBrightBlack: Color(0xFF75715E),
    terminalBrightRed: Color(0xFFF92672),
    terminalBrightGreen: Color(0xFFA6E22E),
    terminalBrightYellow: Color(0xFFF4BF75),
    terminalBrightBlue: Color(0xFF66D9EF),
    terminalBrightMagenta: Color(0xFFAE81FF),
    terminalBrightCyan: Color(0xFFA1EFE4),
    terminalBrightWhite: Color(0xFFF9F8F5),
    accent: Color(0xFFF92672),
    success: Color(0xFFA6E22E),
    error: Color(0xFFF92672),
    warning: Color(0xFFF4BF75),
    border: Color(0xFF49483E),
    divider: Color(0xFF49483E),
    hover: Color(0xFF3E3D32),
    cardBackground: Color(0xFF3E3D32),
    inputBackground: Color(0xFF49483E),
  );

  // Gruvbox Dark theme
  static const gruvboxDark = AppColors(
    primary: Color(0xFFFE8019),
    secondary: Color(0xFFB8BB26),
    background: Color(0xFF282828),
    surface: Color(0xFF3C3836),
    surfaceSecondary: Color(0xFF504945),
    textPrimary: Color(0xFFEBDBB2),
    textSecondary: Color(0xFFBDAE93),
    textTertiary: Color(0xFF928374),
    terminalBackground: Color(0xFF282828),
    terminalForeground: Color(0xFFEBDBB2),
    terminalCursor: Color(0xFFFBF1C7),
    terminalSelection: Color(0xFF504945),
    terminalPrompt: Color(0xFFB8BB26),
    terminalBlack: Color(0xFF282828),
    terminalRed: Color(0xFFCC241D),
    terminalGreen: Color(0xFF98971A),
    terminalYellow: Color(0xFFD79921),
    terminalBlue: Color(0xFF458588),
    terminalMagenta: Color(0xFFB16286),
    terminalCyan: Color(0xFF689D6A),
    terminalWhite: Color(0xFFA89984),
    terminalBrightBlack: Color(0xFF928374),
    terminalBrightRed: Color(0xFFFB4934),
    terminalBrightGreen: Color(0xFFB8BB26),
    terminalBrightYellow: Color(0xFFFABD2F),
    terminalBrightBlue: Color(0xFF83A598),
    terminalBrightMagenta: Color(0xFFD3869B),
    terminalBrightCyan: Color(0xFF8EC07C),
    terminalBrightWhite: Color(0xFFEBDBB2),
    accent: Color(0xFFFE8019),
    success: Color(0xFFB8BB26),
    error: Color(0xFFFB4934),
    warning: Color(0xFFFABD2F),
    border: Color(0xFF504945),
    divider: Color(0xFF504945),
    hover: Color(0xFF3C3836),
    cardBackground: Color(0xFF3C3836),
    inputBackground: Color(0xFF504945),
  );

  // One Dark theme
  static const oneDark = AppColors(
    primary: Color(0xFF61AFEF),
    secondary: Color(0xFFC678DD),
    background: Color(0xFF282C34),
    surface: Color(0xFF21252B),
    surfaceSecondary: Color(0xFF2C313C),
    textPrimary: Color(0xFFABB2BF),
    textSecondary: Color(0xFF5C6370),
    textTertiary: Color(0xFF4B5263),
    terminalBackground: Color(0xFF282C34),
    terminalForeground: Color(0xFFABB2BF),
    terminalCursor: Color(0xFF528BFF),
    terminalSelection: Color(0xFF3E4451),
    terminalPrompt: Color(0xFF98C379),
    terminalBlack: Color(0xFF282C34),
    terminalRed: Color(0xFFE06C75),
    terminalGreen: Color(0xFF98C379),
    terminalYellow: Color(0xFFE5C07B),
    terminalBlue: Color(0xFF61AFEF),
    terminalMagenta: Color(0xFFC678DD),
    terminalCyan: Color(0xFF56B6C2),
    terminalWhite: Color(0xFFABB2BF),
    terminalBrightBlack: Color(0xFF5C6370),
    terminalBrightRed: Color(0xFFE06C75),
    terminalBrightGreen: Color(0xFF98C379),
    terminalBrightYellow: Color(0xFFE5C07B),
    terminalBrightBlue: Color(0xFF61AFEF),
    terminalBrightMagenta: Color(0xFFC678DD),
    terminalBrightCyan: Color(0xFF56B6C2),
    terminalBrightWhite: Color(0xFFFFFFFF),
    accent: Color(0xFF61AFEF),
    success: Color(0xFF98C379),
    error: Color(0xFFE06C75),
    warning: Color(0xFFE5C07B),
    border: Color(0xFF181A1F),
    divider: Color(0xFF181A1F),
    hover: Color(0xFF2C313C),
    cardBackground: Color(0xFF21252B),
    inputBackground: Color(0xFF2C313C),
  );

  // Tokyo Night theme
  static const tokyoNight = AppColors(
    primary: Color(0xFF7AA2F7),
    secondary: Color(0xFFBB9AF7),
    background: Color(0xFF1A1B26),
    surface: Color(0xFF24283B),
    surfaceSecondary: Color(0xFF414868),
    textPrimary: Color(0xFFC0CAF5),
    textSecondary: Color(0xFF9AA5CE),
    textTertiary: Color(0xFF565F89),
    terminalBackground: Color(0xFF1A1B26),
    terminalForeground: Color(0xFFC0CAF5),
    terminalCursor: Color(0xFFC0CAF5),
    terminalSelection: Color(0xFF2E3C64),
    terminalPrompt: Color(0xFF9ECE6A),
    terminalBlack: Color(0xFF15161E),
    terminalRed: Color(0xFFF7768E),
    terminalGreen: Color(0xFF9ECE6A),
    terminalYellow: Color(0xFFE0AF68),
    terminalBlue: Color(0xFF7AA2F7),
    terminalMagenta: Color(0xFFBB9AF7),
    terminalCyan: Color(0xFF7DCFFF),
    terminalWhite: Color(0xFFA9B1D6),
    terminalBrightBlack: Color(0xFF414868),
    terminalBrightRed: Color(0xFFF7768E),
    terminalBrightGreen: Color(0xFF9ECE6A),
    terminalBrightYellow: Color(0xFFE0AF68),
    terminalBrightBlue: Color(0xFF7AA2F7),
    terminalBrightMagenta: Color(0xFFBB9AF7),
    terminalBrightCyan: Color(0xFF7DCFFF),
    terminalBrightWhite: Color(0xFFC0CAF5),
    accent: Color(0xFF7AA2F7),
    success: Color(0xFF9ECE6A),
    error: Color(0xFFF7768E),
    warning: Color(0xFFE0AF68),
    border: Color(0xFF292E42),
    divider: Color(0xFF292E42),
    hover: Color(0xFF414868),
    cardBackground: Color(0xFF24283B),
    inputBackground: Color(0xFF414868),
  );

  // Catppuccin Mocha theme
  static const catppuccinMocha = AppColors(
    primary: Color(0xFF89B4FA),
    secondary: Color(0xFFF5C2E7),
    background: Color(0xFF1E1E2E),
    surface: Color(0xFF313244),
    surfaceSecondary: Color(0xFF45475A),
    textPrimary: Color(0xFFCDD6F4),
    textSecondary: Color(0xFFBAC2DE),
    textTertiary: Color(0xFF6C7086),
    terminalBackground: Color(0xFF1E1E2E),
    terminalForeground: Color(0xFFCDD6F4),
    terminalCursor: Color(0xFFF5E0DC),
    terminalSelection: Color(0xFF585B70),
    terminalPrompt: Color(0xFFA6E3A1),
    terminalBlack: Color(0xFF45475A),
    terminalRed: Color(0xFFF38BA8),
    terminalGreen: Color(0xFFA6E3A1),
    terminalYellow: Color(0xFFF9E2AF),
    terminalBlue: Color(0xFF89B4FA),
    terminalMagenta: Color(0xFFF5C2E7),
    terminalCyan: Color(0xFF94E2D5),
    terminalWhite: Color(0xFFBAC2DE),
    terminalBrightBlack: Color(0xFF585B70),
    terminalBrightRed: Color(0xFFF38BA8),
    terminalBrightGreen: Color(0xFFA6E3A1),
    terminalBrightYellow: Color(0xFFF9E2AF),
    terminalBrightBlue: Color(0xFF89B4FA),
    terminalBrightMagenta: Color(0xFFF5C2E7),
    terminalBrightCyan: Color(0xFF94E2D5),
    terminalBrightWhite: Color(0xFFA6ADC8),
    accent: Color(0xFF89B4FA),
    success: Color(0xFFA6E3A1),
    error: Color(0xFFF38BA8),
    warning: Color(0xFFF9E2AF),
    border: Color(0xFF45475A),
    divider: Color(0xFF45475A),
    hover: Color(0xFF585B70),
    cardBackground: Color(0xFF313244),
    inputBackground: Color(0xFF45475A),
  );

  // Material theme
  static const material = AppColors(
    primary: Color(0xFF82AAFF),
    secondary: Color(0xFFC792EA),
    background: Color(0xFF263238),
    surface: Color(0xFF2E3C43),
    surfaceSecondary: Color(0xFF37474F),
    textPrimary: Color(0xFFEEFFFF),
    textSecondary: Color(0xFFB0BEC5),
    textTertiary: Color(0xFF546E7A),
    terminalBackground: Color(0xFF263238),
    terminalForeground: Color(0xFFEEFFFF),
    terminalCursor: Color(0xFFFFCC00),
    terminalSelection: Color(0xFF37474F),
    terminalPrompt: Color(0xFFC3E88D),
    terminalBlack: Color(0xFF000000),
    terminalRed: Color(0xFFF07178),
    terminalGreen: Color(0xFFC3E88D),
    terminalYellow: Color(0xFFFFCB6B),
    terminalBlue: Color(0xFF82AAFF),
    terminalMagenta: Color(0xFFC792EA),
    terminalCyan: Color(0xFF89DDFF),
    terminalWhite: Color(0xFFFFFFFF),
    terminalBrightBlack: Color(0xFF546E7A),
    terminalBrightRed: Color(0xFFF07178),
    terminalBrightGreen: Color(0xFFC3E88D),
    terminalBrightYellow: Color(0xFFFFCB6B),
    terminalBrightBlue: Color(0xFF82AAFF),
    terminalBrightMagenta: Color(0xFFC792EA),
    terminalBrightCyan: Color(0xFF89DDFF),
    terminalBrightWhite: Color(0xFFFFFFFF),
    accent: Color(0xFF82AAFF),
    success: Color(0xFFC3E88D),
    error: Color(0xFFF07178),
    warning: Color(0xFFFFCB6B),
    border: Color(0xFF37474F),
    divider: Color(0xFF37474F),
    hover: Color(0xFF2E3C43),
    cardBackground: Color(0xFF2E3C43),
    inputBackground: Color(0xFF37474F),
  );

  // Horizon theme
  static const horizon = AppColors(
    primary: Color(0xFF25B0BC),
    secondary: Color(0xFFE95678),
    background: Color(0xFF1C1E26),
    surface: Color(0xFF232530),
    surfaceSecondary: Color(0xFF2E303E),
    textPrimary: Color(0xFFE3E6EE),
    textSecondary: Color(0xFF9DA0A2),
    textTertiary: Color(0xFF6C6F93),
    terminalBackground: Color(0xFF1C1E26),
    terminalForeground: Color(0xFFE3E6EE),
    terminalCursor: Color(0xFFF09483),
    terminalSelection: Color(0xFF2E303E),
    terminalPrompt: Color(0xFF29D398),
    terminalBlack: Color(0xFF16161C),
    terminalRed: Color(0xFFE95678),
    terminalGreen: Color(0xFF29D398),
    terminalYellow: Color(0xFFFAB795),
    terminalBlue: Color(0xFF26BBD9),
    terminalMagenta: Color(0xFFEE64AC),
    terminalCyan: Color(0xFF59E3E3),
    terminalWhite: Color(0xFFE3E6EE),
    terminalBrightBlack: Color(0xFF5B5858),
    terminalBrightRed: Color(0xFFEC6A88),
    terminalBrightGreen: Color(0xFF3FDAA4),
    terminalBrightYellow: Color(0xFFFBC3A7),
    terminalBrightBlue: Color(0xFF3FC4DE),
    terminalBrightMagenta: Color(0xFFF075B5),
    terminalBrightCyan: Color(0xFF6BE6E6),
    terminalBrightWhite: Color(0xFFF9F9F9),
    accent: Color(0xFF25B0BC),
    success: Color(0xFF29D398),
    error: Color(0xFFE95678),
    warning: Color(0xFFFAB795),
    border: Color(0xFF2E303E),
    divider: Color(0xFF2E303E),
    hover: Color(0xFF232530),
    cardBackground: Color(0xFF232530),
    inputBackground: Color(0xFF2E303E),
  );
}
